DO $$
DECLARE
  r RECORD;
  seq_name text;
  next_val bigint;
BEGIN
  -- List of (table, surrogate_key_column)
  FOR r IN
    SELECT * FROM (VALUES
      ('DimProduct',     'ProductKey'),
      ('DimCustomer',    'CustomerKey'),
      ('DimPromotion',   'PromotionKey'),
      ('DimSalesReason', 'SalesReasonKey'),
      ('DimShipMethod',  'ShipMethodKey'),
      ('DimStore',       'StoreKey'),
      ('DimTerritory',   'TerritoryKey'),
      ('FactSales',      'FactSalesKey')
    ) AS v(table_name, sk_col)
  LOOP
    -- 1) Ensure the SK column auto-generates (identity or nextval default)
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'dwh'
        AND table_name   = r.table_name
        AND column_name  = r.sk_col
        AND (column_default LIKE 'nextval%' OR is_identity = 'YES')
    ) THEN
      EXECUTE format(
        'ALTER TABLE dwh.%I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
        r.table_name, r.sk_col
      );
      RAISE NOTICE '%: added identity on %', r.table_name, r.sk_col;
    END IF;

    -- 2) Sync the sequence to MAX(key)+1 (safe if table is empty too)
    SELECT pg_get_serial_sequence(format('dwh.%I', r.table_name), r.sk_col)
      INTO seq_name;

    IF seq_name IS NOT NULL THEN
      EXECUTE format(
        'SELECT COALESCE(MAX(%I),0) + 1 FROM dwh.%I',
        r.sk_col, r.table_name
      ) INTO next_val;

      EXECUTE format('SELECT setval(%L, %s, false)', seq_name, next_val);
      RAISE NOTICE '%: sequence % set to %', r.table_name, seq_name, next_val;
    ELSE
      RAISE WARNING '%: no sequence found for %. Is the column identity/serial?',
                     r.table_name, r.sk_col;
    END IF;
  END LOOP;
END $$;